name = "nexshore-website"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "nexshore-db"
database_id = "615d78af-64a4-4803-a857-3306547396bc"
